### ISSUE TITLE
add screenshots or frontend demo

### ISSUE THREAD

**Issue by tal32123** [troncali/nest-vue#24]
Can you please add screenshots or demo of frontend so devs can see if its relevant for them? Thanks.

**Comment by troncali** [comment]
Hi there - a demo is available at https://vxnn.troncali.com/demo/.  The demo site uses VuePress, which is a static site generator based on Vue.

The frontend app in the repo is currently just the [standard files scaffolded by vue](https://next.cli.vuejs.org/guide/creating-a-project.html).  More will be added to the demo as things are built out, but there are no specific frontend components yet.
